name: modeling-training
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - flit-core=3.8.0=py310h06a4308_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py310h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-base=3.6.2=py310h945d387_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py310h06a4308_1
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.23.5=py310hd5efca6_0
  - numpy-base=1.23.5=py310h8e6c178_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=22.0=py310h06a4308_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.10=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=2.0.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_3
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_1
  - seaborn=0.12.2=py310h06a4308_0
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.0=py310_cu118
  - torchtriton=2.0.0=py310
  - torchvision=0.15.0=py310_cu118
  - typing_extensions=4.4.0=py310h06a4308_0
  - urllib3=1.26.15=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.4=hc292b87_0
  - pip:
      - accelerate==0.20.3
      - hmmlearn>=0.3.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - apache-beam==2.48.0
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==22.2.0
      - cloudpickle==2.2.1
      - crcmod==1.7
      - datasets==2.11.0
      - dill==0.3.1.1
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.6.0
      - evaluate==0.4.0
      - fastavro==1.7.4
      - fasteners==0.18
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - grpcio==1.54.2
      - hdfs==2.7.0
      - httplib2==0.22.0
      - huggingface-hub==0.15.1
      - joblib==1.2.0
      - mpmath==1.2.1
      - multidict==6.0.4
      - multiprocess==0.70.14
      - mwparserfromhell==0.6.4
      - objsize==0.6.1
      - orjson==3.9.0
      - pandas==2.0.0
      - pathtools==0.1.2
      - proto-plus==1.22.2
      - protobuf==4.22.1
      - psutil==5.9.4
      - pyarrow==11.0.0
      - pydot==1.4.2
      - pymongo==4.3.3
      - pytz==2023.3
      - pyyaml==6.0
      - regex==2023.3.23
      - responses==0.18.0
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.19.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - tqdm==4.65.0
      - transformers==4.30.2
      - tzdata==2023.3
      - wandb==0.14.0
      - xxhash==3.2.0
      - yarl==1.8.2
      - zstandard==0.21.0
